= Component Module
:table-caption!:

The Component Module contains the component Library.

[cols="1,5a",separator="!"]
!===
!Dependencies
! xref:/lua/api/FullReflectionModule.adoc[FullReflectionModule]
!===

== Globals

=== **component**
The component library contains functions that allow interaction with the component network.

=== __component.__**findComponent** ((string query | xref:/reflection/classes/Class.adoc[Class] type)...) -> string[]...
Searches the component network for components with the given query or have the given type. +
You can pass multiple parameters and each parameter will be handled separately and returns a corresponding return value.

[%collapsible]
====
.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Query* `...`
! string | Object-Class
! A nick/group query as string or a class for the components in the network you try to find.

!===
.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *UUIDs* `...`
! string[]
! List of network component UUIDs which pass the given nick query or are of the given type.

!===
====

=== __component.__**proxy** ((id: string | ids: string[])...) -> (xref:/reflection/classes/Object.adoc[Object] | xref:/reflection/classes/Object.adoc[Object][])...
Generates and returns instances of the network components with the given UUIDs. +
You can pass any amount of parameters and each parameter will then have a corresponding return value. +
Each parameter can be either a string, or an array of strings.
These strings should then contain just the UUID of a network component. +
If a network component cannot be found for a given string, nil will be used for the return.
Otherwise, an instance of the network component will be returned. +
If a parameter is a string array, the return value will be an array of network component instances.

[%collapsible]
====
.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *ID[s]* `...`
! string | string[]
! The UUID[-Arrays] of the network component[s].

!===
.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Object[s]* `...`
! xref:/reflection/classes/Object.adoc[Object] | xref:/reflection/classes/Object.adoc[Object][] | nil
! The Network-Component[-Array]s associated with the UUIDs, nil if the UUID was not found.

!===
====

