= Computer API
:description: The Computer API allows you to manage the computer itself.

The Computer API provides a interface to the computer owns functionalities.

== Functions

=== `beep(number pitch)`

Lets the computer to emit a simple beep sound with the given pitch.

Parameter::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|pitch
|number
|The pitch of the beep sound you want to play.
|===

=== `stop()`

Stops the current code execution.

Basically kills the PC runtime immediately.

=== `panic(string error)`

Crashes the computer with the given error message.

Parameter::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|error
|string
|The crash error message you want to use
|===

=== `reset()`

Stops the current code execution immediately and queues the system to restart in the next tick.

=== `skip()`

If the tick is in the second Lua tick stage, the function will yield the runtime for the tick.
If it is in the first Lua tick stage, the function will simply do nothing.

Withit you can prevent a out of time exception to occur.

=== `string getEEPROM()`

Returns the code the current eeprom contains.

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|string
|string
|The code in the EEPROM
|===

=== `setEEPROM(string code)`

Sets the code of the current eeprom. Doesn't cause a system reset.

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|code
|string
|The code you want to place into the eeprom.
|===

=== `number time()`

Returns the number of game seconds passed since the save got created.
A game day consists of 24 game hours, a game hour consists of 60 game minutes, a game minute consists of 60 game seconds.

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|number
|number
|The number of game seconds passed since the save got created.
|===

=== `int millis()`

Retruns the amount of milliseconds passed since the system started.

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|int
|int
|Amount of milliseconds since system start
|===

=== `GPU[] getGPUs()`

This function allows you to retrieve the list of all GPUs built into the computer.

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|GPU[]
|GPU[]
|A array containing instances for each GPU built into the computer.
|===

=== `Screen[] getScreens()`

This function allows you to retrieve the list of all Screens built into the computer (not own components).

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|Screen[]
|Screen[]
|A array containing instances for every Screen built into the computer.
|===



include::partial$api_footer.adoc[]