= Event Module
:table-caption!:



== Globals

=== **event**
The Event API provides classes, functions and variables for interacting with the component network.

=== __event.__**clear** ()
Clears every signal from the signal queue.

=== __event.__**filter** (...) -> xref:/reflection/structs/EventFilter.adoc[EventFilter]
Creates an Event filter expression.

=== __event.__**ignore** (xref:/reflection/classes/Object.adoc[Object]...)
Removes the running lua context from the listen queue of the given components. Basically the opposite of listen.

=== __event.__**ignoreAll** ()
Stops listening to any signal sender. If afterwards there are still coming signals in, it might be the system itself or caching bug.

=== __event.__**listen** (xref:/reflection/classes/Object.adoc[Object]...)
Adds the running lua context to the listen queue of the given components.

=== __event.__**listening** () -> xref:/reflection/classes/Object.adoc[Object][]
Returns all signal senders this computer is listening to.

[%collapsible]
====
.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *An array containing all objects this computer is currently listening to.* `listening`
! xref:/reflection/classes/Object.adoc[Object][]
! 

!===
====

=== __event.__**pull** ([timeout: number]) -> (string|nil, xref:/reflection/classes/Object.adoc[Object], ...)
Waits for a signal in the queue. Blocks the execution until a signal got pushed to the signal queue, or the timeout is reached. +
Returns directly if there is already a signal in the queue (the tick doesn￢ﾀﾙt get yielded).

[%collapsible]
====
.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Timeout* `timeout`
! number
! The amount of time needs to pass until pull unblocks when no signal got pushed. If not set, the function will block indefinitely until a signal gets pushed. If set to `0` (int), will not yield the tick and directly return with the signal data or nil if no signal was in the queue.

!===
.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Event* `event`
! string|nil
! The name of the returned signal. Nil when timeout got reached.

! *Sender* `sender`
! xref:/reflection/classes/Object.adoc[Object]
! The component representation of the signal sender. Not set when timeout got reached.

! *Parameters* `parameters`
! any...
! The parameters passed to the signal. Not set when timeout got reached.

!===
====

