= File-System Module
:table-caption!:

FicsIt-Networks implements it’s own virtual filesystem for UNIX like experience using the FileSystem.
The file system consists of nodes. Such a node can be a File, a Folder or something else. Each nodes is able to have child nodes and might be able to get opened with a file stream. A folder also delivers an abstract interface for adding and removing nodes. A Device implements lookup functions for searching for nodes in the filesystem structure. Such a device can be a temporary filesystem (tmpfs) which exists only in memory and which will get purged on a system reboot, or f.e. a disk filesystem (drives) which store the nodes on the real virtual filesystem in a folder. You can then mount such a device to a location in the root filesystem tree so when you now access a path, the filesystem looks first for the device and uses then the remaining path to get the node data from the device.
There is also a DriveNode which simply holds a reference to a drive so you can access a drive via the filesystem. You can use then the mount function to mount the Drive of a DriveNode to the given location in the filesystem tree.
Because you need at least one drive mounted to even be able to access any node, we provide the initFileSystem function which you can call only once in a system session. This functions will then mount the DevDevice to the given location.
The DevDevice is a sepcial Device which holds all the DeviceNodes representing Device attached to the computer session, like hard drives, tempfs and the serial I/O.

== Globals

=== **filesystem**
The filesystem api provides structures, functions and variables for interacting with the virtual file systems.
You can't access files outside the virtual filesystem. If you try to do so, the Lua runtime crashes.

=== __filesystem.__**analyzePath** (string...) -> int...
Each provided string will be viewed as one filesystem-path and will be checked for lexical features. +
Each of those string will then have a integer return value which is a bit-flag-register describing those lexical features.

.Bit-Flags
[%collapsible]
====
[cols="1,10a"]
|===
| 1 | Is filesystem root
| 2 | Is Empty (includes if it is root-path)
| 3 | Is absolute path
| 4 | Is only a file/folder name
| 5 | Filename has extension
| 6 | Ends with a `/` -> refers a directory
|===
====

=== __filesystem.__**children** (path: string) -> string[]
Lists all children names of the node with the given path. (f.e. items in a folder)

=== __filesystem.__**createDir** (path: string, recursive: bool) -> bool
Creates the folder path.

[%collapsible]
====
.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Path* `path`
! string
! folder path the function should create

! *Recursive* `recursive`
! bool
! If false creates only the last folder of the path. If true creates all folders in the path.

!===
.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Success* `success`
! bool
! Returns true if it was able to create the directory.

!===
====

=== __filesystem.__**doFile** (path: string) -> ...
Executes Lua code in the file referd by the given path.

Function fails if path doesn￢ﾀﾙt exist or path doesn￢ﾀﾙt refer to a file.

Returns the result of the execute function or what ever it yielded

=== __filesystem.__**exists** (path: string) -> bool
Returns true if the given path exists.

=== __filesystem.__**initFileSystem** (path: string) -> bool
Trys to mount the system DevDevice to the given location.
The DevDevice is special Device holding DeviceNodes for all filesystems added to the system. (like TmpFS and drives). It is unmountable as well as getting mounted a seccond time.

[%collapsible]
====
.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Path* `path`
! string
! path to the mountpoint were the dev device should get mounted to

!===
.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Success* `success`
! bool
! returns if it was able to mount the DevDevice

!===
====

=== __filesystem.__**isDir** (path: string) -> bool
Returns true if the given path refers to directory.

=== __filesystem.__**isFile** (path: string) -> bool
Returns true if the given path refers to a file.

=== __filesystem.__**isNode** (string...) -> bool...
For each given string, returns a bool to tell if string is a valid node (file/folder) name.

=== __filesystem.__**loadFile** (path: string) -> function
Loads the file refered by the given path as a Lua function and returns it.
Functions fails if path doesn￢ﾀﾙt exist or path doesn￢ﾀﾙt reger to a file.

=== __filesystem.__**makeFileSystem** (type: string, name: string) -> bool
Trys to create a new file system of the given type with the given name.
The created filesystem will be added to the system DevDevice.

.Possible Types:
[%collapsible]
====
* `tmpfs`
+
A temporary filesystem only existing at runtime in the memory of your computer. All data will be lost when the system stops.
====

[%collapsible]
====
.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Type* `type`
! string
! the type of the new filesystem

! *Name* `name`
! string
! the name of the new filesystem you want to create

!===
.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Success* `success`
! bool
! returns true if it was able to create the new filesystem

!===
====

=== __filesystem.__**meta** (string...) -> string...
Returns for each given string path, a table that defines contains some meta information about node the string references.

.Possible `type`-Field strings
[%collapsible]
====
[cols="1,10a"]
| ===
| `File`			| A normal File
| `Directory`	| A directory or folder that can hold multiple nodes.
| `Device`		| A special type of Node that represents a filesystem and can be mounted.
| `Unknown`		| The node type is not known to this utility function.
| ===
====

=== __filesystem.__**mount** (device: string, mountPoint: string) -> bool
This function mounts the device referenced by the the path to a device node to the given mount point.

[%collapsible]
====
.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Device* `device`
! string
! the path to the device you want to mount

! *Mount Point* `mountPoint`
! string
! the path to the point were the device should get mounted to

!===
.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Success* `success`
! bool
! true if the mount was executed successfully

!===
====

=== __filesystem.__**move** (from: string, to: string) -> bool
Moves the filesystem object from the given path to the other given path.

Function fails if it is not able to move the object.

[%collapsible]
====
.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *From* `from`
! string
! path to the filesystem object you want to move

! *To* `to`
! string
! path to the filesystem object the target should get moved to

!===
.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Success* `success`
! bool
! returns true if it was able to move the node

!===
====

=== __filesystem.__**open** (path: string, mode: string) -> xref:/lua/api/FileSystem.adoc#_file[File]
Opens a file-stream and returns it as File-table.

.Possible Modes
[%collapsible]
====
[cols="1,1,4a"]
|===
| `r` | read only
| File-Stream can just read from file. +
  If file doesn￢ﾀﾙt exist, open will return nil
| `w` | write
| File-Stream can read and write. +
  Creates the file if it doesn￢ﾀﾙt exist
| `a` | end of file
| File-Stream can read and write. +
  Cursor is set to the end of file.
| `+r` | truncate
| File-Stream can read and write. +
  All previous data in file gets dropped
| `+a` | append
| File-Stream can read the full file, +
  but can only write to the end of the existing file.
|===
====

[%collapsible]
====
.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Path* `path`
! string
! the path to the file you want to open a file-stream for

! *Mode* `mode`
! string
! The mode for the file stream

!===
.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *File* `file`
! xref:/lua/api/FileSystem.adoc#_file[File]
! The File table of the file stream. Nil if not able to open file in read only.

!===
====

=== __filesystem.__**path** ([int,] string...) -> string
Combines a variable amount of strings as paths together to one big path.

Additionally, applies given conversion. Defined by the optionally given integer.

.Possible Conversions
[%collapsible]
====
[cols="1,10a"]
|===
| 0 | Normalize the path. +
      `/my/../weird/./path` -> `/weird/path`
| 1 | Normalizes and converts the path to an absolute path. +
      `my/abs/path` -> `/my/abs/path`
| 2 | Normalizes and converts the path to an relative path. +
      `/my/relative/path` -> `my/relative/path`
| 3 | Returns the whole file/folder name. +
      `/path/to/file.txt` -> `file.txt`
| 4 | Returns the stem of the filename. +
      `/path/to/file.txt` -> `file` +
      `/path/to/.file` -> `.file`
| 5 | Returns the file-extension of the filename. +
      `/path/to/file.txt` -> `.txt` +
      `/path/to/.file` -> empty-str +
      `/path/to/file.` -> `.`
|===
====

=== __filesystem.__**remove** (path: string, recursive: bool) -> bool
Removes the filesystem object at the given path.

[%collapsible]
====
.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Path* `path`
! string
! path to the filesystem object

! *Recursive* `recusive`
! bool
! If false only removes the given filesystem object. If true removes all childs of the filesystem object.

!===
.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Success* `success`
! bool
! Returns true if it was able to remove the node

!===
====

=== __filesystem.__**removeFileSystem** (name: string) -> bool
Tries to remove the filesystem with the given name from the system DevDevice.
All mounts of the device will run invalid.

[%collapsible]
====
.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Name* `name`
! string
! the name of the new filesystem you want to remove

!===
.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Success* `success`
! bool
! returns true if it was able to remove the new filesystem

!===
====

=== __filesystem.__**rename** (path: string, name: string) -> bool
Renames the filesystem object at the given path to the given name.

[%collapsible]
====
.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Path* `path`
! string
! path to the filesystem object you want to rename

! *Name* `name`
! string
! the new name for your filesystem object

!===
.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Success* `success`
! bool
! returns true if it was able to rename the node

!===
====

=== __filesystem.__**unmount** (mountPoint: string) -> bool
This function unmounts if the device at the given mount point.

[%collapsible]
====
.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Mount Point* `mountPoint`
! string
! the path the device is mounted to

!===
.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Success* `success`
! bool
! returns true if it was able to unmount the device located at the mount point

!===
====

== Types

=== **File**


=== __File.__**close** ()
Closes the File-Stream.

=== __File.__**read** (int...) -> string...
Reads up to the given amount of bytes from the file.
Strings may be smaller than the given amount of bytes due to f.e. reaching the End-Of-File.

=== __File.__**seek** (where: string, offset: int) -> int
Moves the File-Streams pointer to a position defined by the offset and from what starting location.

.Possble `where` values
[%collapsible]
====
* `cur` Offset is relative to the current location
* `set` Offset is relative to the beginning of the file
* `end` Offset is relative to the end of the file
====

=== __File.__**write** (string...)
Writes the given strings to the File-Stream.

