= Inventory API

The inventory api contains structures, functions and variables related to ingame inventorys, items and more.

== Inventory

A lua table representation of a ingame inventory containing stacks of items.

=== Functions

==== `ItemStack... getStack(int index...)`

Returns the item stacks at the given indexes.

Parameters::
+
[cols="1,1,~"]
|===
|Name |Type |Description

|index...
|int
|indexes of slots in the inventory
|===

Return Values::
+
[cols="1,1,~"]
|===
|Name |Type |Description

|ItemStack...
|ItemStack
|ItemStacks at the given slots in the inventory
|===

==== `int getItemCount(int index)`

Returns the amount of items of the stack at the given index.

Parameters::
+
[cols="1,1,~"]
|===
|Name |Type |Description

|index
|int
|the slot index you want to know the amount of items from
|===

Return Values::
+
[cols="1,1,~"]
|===
|Name |Type |Description

|int
|int
|the count of items in the given slot
|===

==== `int getSize()`

Returns the count of slots in the inventory

Return Values::
+
[cols="1,1,~"]
|===
|Name |Type |Description

|int
|int
|Count of slots in the inventory
|===

==== `sort()`

Sorts the inventory

== FactoryConnector

A FactoryConnector is a connection point of a actor for a conveyor or pipe.

=== Functions

==== `int getType()`

Returns the type of connector.

- 0: Conveyor
- 1: Pipe
[]

Return Values::
+
[cols="1,1,~"]
|===
|Name |Type |Description

|int
|int
|type of connector
|===

==== `int getDirection()`

Returns the direction of the connector.

- 0: Input
- 1: Output
- 2: Any
- 4: Snap only (like conveyor poles)
[]

Return Values::
+
[cols="1,1,~"]
|===
|Name |Type |Description

|int
|int
|direction of the connector
|===

==== `bool isConnected()`

Checks if the connector is connected.

Return Values::
+
[cols="1,1,~"]
|===
|Name |Type |Description

|bool
|bool
|true if connector is connected
|===

==== `Inventory getInventory()`

Returns the internal inventory of the connector

Return Values::
+
[cols="1,1,~"]
|===
|Name |Type |Description

|Inventory
|Inventory
|the internal inventory
|===

==== `FactoryHook hook()`

Attachs and returns a factory hook for the connector.

If a hook is already attached, returns the hook.

Return Values::
+
[cols="1,1,~"]
|===
|Name |Type |Description

|FactoryHook
|FactoryHook
|a factory hook attached to the connector
|===

== Recipe

A recipe for a manufacturer with multiple inputs and outputs as well as other information like process time.

=== Functions

==== `string getName()`

Returns the name of the recipe

Return Values::
+
[cols="1,1,~"]
|===
|Name |Type |Description

|string
|string
|name of the recipe
|===

==== `ItemCount[] getProducts()`

Returns the products of the recipe.

Return Values::
+
[cols="1,1,~"]
|===
|Name |Type |Description

|ItemCount[]
|ItemCount[]
|A array of tables containing `int count` for the count of items and `ItemType item` for the type of item
|===

==== `ItemCount[] getIngredients()``

Returns the ingredients needed for the recipe.

Return Values::
+
[cols="1,1,~"]
|===
|Name |Type |Description

|ItemCount[]
|ItemCount[]
|A array of tables containing `int count` for the count of items and `ItemType item` for the type of item
|===

==== `num getDuration()`

Returns the amount of time needed to process the recipe with a potential of 100%.

Return Values::
+
[cols="1,1,~"]
|===
|Name |Type |Description

|num
|num
|amount of time in seconds
|===

== ItemStack

Combines a Item and a count to a stack of items.

=== Variables

==== `int count`

The count of items the stack contains.

==== `Item item`

They item information of the stack.

== Item

One Item or basically a structure defining item information like the type and the item state.

=== Variables

==== `ItemType type`

Defines the type of the item.

== ItemType

The type of a item. Used f.e. in Item to define the type.

=== Functions

==== `string getName()`

Returns the name of the item.

Return Values::
+
[cols="1,1,~"]
|===
|Name |Type |Description

|string
|string
|the name of the item
|===

== FactoryHook

The factory hook is a special table used to hook a factory connector. This hook allows you to get signals when the connector transfers a item and to get some stats about the runtime pehavior of the the factory connector.

This system uses a reference counter to determine if the hook should exist.
That means as long as you have at least one reference to the same factoryhook representation table or multiple different tables but refering to the same hook, the hook exists. If the Lua garbage collector frees such a table, and there is no other table refering to the same hook, the hook will get destroyed.

Because the FactoryHook is no component, you can't use the component api to listen to the signals provided by the hook. To do that the hook table provides its own function.

=== Functions

==== `int getIlastM()`

Returns the count of items transfered in the last minute.

Return Values::
+
[cols="1,1,~"]
|===
|Name |Type |Description

|int
|int
|count of items transfered in the last minute
|===

==== `listen()`

Subscribes the executing computer to the signals of the hook.



include::partial$api_footer.adoc[]