= Inventory API
:description: The Inventory API allows you to interact with ingame inventories.

The inventory API contains structures, functions, and variables related to ingame inventories, items, and more.

== Inventory

A lua table representation of an ingame inventory containing stacks of items.

=== Functions

==== `ItemStack... getStack(int index...)`

Returns the item stacks at the given indexes.

Parameters::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|index...
|int
|indexes of slots in the inventory
|===

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|ItemStack...
|ItemStack
|ItemStacks at the given slots in the inventory
|===

==== `int getItemCount()`

Returns the total count of all item amounts.

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|int
|int
|the total count of all item amounts
|===

==== `int getSize()`

Returns the inventory slot count.

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|int
|int
|the inventory slot count.
|===

==== `sort()`

Sorts the inventory

== FactoryConnector

A FactoryConnector is a connection point of an actor for a conveyor or pipe.

=== Functions

==== `int getType()`

Returns the type of connector.

- 0: Conveyor
- 1: Pipe

[]
Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|int
|int
|type of connector
|===

==== `int getDirection()`

Returns the direction of the connector.

- 0: Input
- 1: Output
- 2: Any
- 4: Snap only (like conveyor poles)

[]
Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|int
|int
|direction of the connector
|===

==== `bool isConnected()`

Checks if the connector is connected.

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|bool
|bool
|true if connector is connected
|===

==== `Inventory getInventory()`

Returns the internal inventory of the connector.

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|Inventory
|Inventory
|the internal inventory
|===

==== `FactoryHook hook()`

Attaches a hook for the connector then returns the hook.

If such is already attached, then just returns it.

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|FactoryHook
|FactoryHook
|a factory hook attached to the connector
|===

== Recipe

A recipe for a manufacturer with multiple inputs and outputs as well as other information like process time.

=== Functions

==== `string getName()`

Returns the name of the recipe

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|string
|string
|name of the recipe
|===

==== `ItemCount[] getProducts()`

Returns the products of the recipe.

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|ItemCount[]
|ItemCount[]
|A array of tables containing `int count` for the count of items and `ItemType item` for the type of item
|===

==== `ItemCount[] getIngredients()``

Returns the ingredients needed for the recipe.

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|ItemCount[]
|ItemCount[]
|A array of tables containing `int count` for the count of items and `ItemType item` for the type of item
|===

==== `num getDuration()`

Returns the amount of time needed to process the recipe with a potential of 100%.

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|num
|num
|amount of time in seconds
|===

== ItemStack

Combines an Item and a count to a stack of items.

=== Variables

==== `int count`

The count of items the stack contains.

==== `Item item`

The item information of the stack.

== Item

One Item or basically a structure defining item information like the type and the item state.

=== Variables

==== `ItemType type`

Defines the type of the item.

== ItemType

The type of an item used f.e. in Item to define the type.

=== Functions

==== `string getName()`

Returns the name of the item.

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|string
|string
|the name of the item
|===

== FactoryHook

The FactoryHook is a special table used to hook onto a FactoryConnector. This hook allows you to get event signals when the connector transfers an item in addition to some stats about its runtime behavior.

This system uses a reference counter to determine whether the hook should exist.
That means, as long as you have at least one reference to the same FactoryHook representation table, or there are multiple different tables referring to the same hook, then the hook will continue to exist. The hook will only get destroyed when the Lua garbage collector determines there are no tables referring to it.

Since the FactoryHook is not a Component, one cannot use the Component API to listen to signals broadcasted by the hook. To do that, use the function provided by the hook.

=== Functions

==== `int getIlastM()`

Returns the count of items transferred in the last minute.


=== Functions

==== `int getIlastM()`

Returns the count of items transferred in the last minute.

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|int
|int
|count of items transfered in the last minute
|===

==== `listen()`

Subscribes the executing computer to the signals of the hook.



include::partial$api_footer.adoc[]
