= Power API
:description: The Power API helps with interacting with the ingame power network.

The power api contains structures, functions and variables related to the ingame power network.

== PowerConnector

A so called actor component which is basically the point of a building where you can connect a power cable to.

=== Functions

==== `PowerInfo getPower()`

Returns the attached power information

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|PowerInfo
|PowerInfo
|The attached power information
|===

==== `PowerCircuit getCircuit()`

Returns the attached power circuit

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|PowerCircuit
|PowerCircuit
|The attached power circuit
|===

=== Properties

==== `int connections (readonly)`

The count of connected power connectors.

==== `int maxConnections (readonly)`

The maximum count of connections this power connector can handle

== PowerInfo

The power information contains information about the power state of one or multiple connectors like stats about production and consumption.

=== Functions

All power related values are in KW.

==== `PowerCircuit getCircuit()`

Returns the used power circuit

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|PowerCircuit
|PowerCircuit
|the used power circuit
|===

=== Properties

==== `number dynProduction (readonly)`

The dynamic production of the last tick.

==== `number baseProduction (readonly)`

The base production of the last tick.

==== `number maxDynProduction (readonly)`

Returns the max amount of dynamic production of the last tick.

==== `number targetConsumption (readonly)`

Returns the target consumption.

==== `number consumption (readonly)`

Returns the amount of actual consumption.

==== `bool hasPower (readonly)`

True if the connector has power.

== Power Circuit

A power circuit itself. Used to get stats about the power production, consumption etc. of the power network.

=== Properties

All power related values in KW.

==== `number production (readonly)`

The amount of power production in the last tick.

==== `number consumption (readonly)`

The amount of power consumption in the last tick.

==== `number capacity (readonly)`

The amount of available power in the last tick.

==== `bool isFuesed (readonly)`

True if the power circuits fuse is triggered.

=== Signals

==== `PowerFuse()`

This signal gets triggered when the power circuits fuse gets triggered because simon forgot to unplug the coffeemachine.



include::partial$api_footer.adoc[]