= Reflection-System Base Module
:table-caption!:

This Module provides common functionallity required by further reflection related modules.

== Types

=== **ReflectionFunction**
Functions of the reflection system are not directly Lua Functions, instead they are this type.
This has various reason, but one neat thing it allows us to do, is to provide documentation capabilities.
Instead of just calling it, you can also ask for information about the function it self.
And it makes debugging a bit easier.

=== __ReflectionFunction.__**asFunctionObject** : xref:/reflection/classes/Function.adoc[Function]
Returns the Reflection-System Object that represents this Reflected Function.
This way you can deeply inspect the function and its associations.

=== __ReflectionFunction.__**callDeferred** : xref:/lua/api/ModuleSystem.adoc#_function[function]
Calls the function deferred in the next tick. Returns a Future to allow check for execution and get the return parameters.

=== __ReflectionFunction.__**quickRef** : string
A string containing the signature and description of the function for quick way to get info one the function within code.

