= Vehicle API

:description: The Vehicle API allows you to interact with vehicles.

The vehicle api provides classes, functions, properties and structs that allow you to interact with differnt kinds of vehicles.

== Vehicle (extends Actor)

This is the base type of all vehicles in the game.

=== Properties

==== `number health (readonly)`

The health of the vehicle.

==== `number maxHealth (readonly)`

The max-health of the vehicle.

==== `bool isSelfDriving`

True if the vehicle is self driving.


== DockingStation

This is the docking station for vehicles like trucks. Which is then able to transfer fuel and items
from and to the vehicle.

=== Functions

==== `Inventory getFuelInv()`

This function returns the inventory of the docking station holding the fuel.

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|Inventory
|Inventory
|The inventory holding the fuel.
|===

==== `Inventory getInv()`

This function returns the inventory of the docking station holding the items which get transfered
from and to the vehicle.

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|Inventory
|Inventory
|The inventory holding the items.
|===

==== `Actor getDocked()`

This function returns the docked actor like the truck.
The actual reference is invalid because for interacting with vehicles you need the vehicle scanner.
But you can use the reference to check the instance with another so you know if f.e. the same vehicle
docked again.

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|Actor
|Actor
|The Actor which is currently docked.
|===

==== `undock()`

Undocks the currently docked actor from the docking station.

=== Properties

==== `bool isLoadMode`

True if the docking station is in load mode.

==== `bool isLoadUnloading`

True if the dockingstation is currently loading or unloading the docked actor.


== WheeledVehicle (Vehicle)

The base class of all vehicles that use wheels for movement (like the sugare cube, truck or explorer).

=== Functions

==== `Inventory getFuelInv()`

This function returns the fuel inventory of the vehicle.

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|Inventory
|Inventory
|The fuel inventory of the vehicle.
|===

==== `Inventory getStorageInv()`

This function returns the storage inventory of the vehicle.
This is the general purpose inventory for the player.

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|Inventory
|Inventory
|The storage inventory of the vehicle.
|===

==== `bool isValidFuel(ItemType item)`

This function allows you to check if a given item type is a valid fuel that can be used for this vehicle.

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|ItemType
|ItemType
|The item type you want to check if the fuel is valid.
|===

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|bool
|bool
|True if the given item type is a valid fuel for this vehicle.
|===

==== `int getCurrentTarget()`

This function returns the index of the target the vehicle currently moves to.

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|int
|int
|The index of the target in the target list this vehicle currently moves to.
|===

==== `nextTarget()`

This function skips the current target and sets it to the next target in the target list.

==== `setCurrentTarget(int target)`

This function allows you to change the current target to the target at the given index in the target list.

Parameters::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|int
|int
|The index of the target in the target list you want to move to.
|===

==== `TargetPoint getTarget(int target)`

This function allows you to get the target point data from the target point at the given index in the target list.

Parameters::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|int
|int
|The index of the target in the target list you want to get the information from.
|===

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|TargetPoint
|TargetPoint
|The target point data of the target point you wanted to get.
|===

==== `removeTarget(int target)`

This function removes the target at the given index from the target list.

Parameters::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|int
|target
|The index of the target in the target list you want to remove.
|===

==== `addTarget(TargetPoint data)`

This function allows you to add a new target point at the end of the target list based of the given target point data.

Parameters::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|data
|TargetPoint
|The target point data of the new target point.
|===

==== `setTarget(int target, TargetPoint data)`

This function allows you to update the target in the target list at the given index with the given target point data.

Parameters::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|target
|int
|The index of the target in the target list you want to update.

|data
|TargetPoint
|The new target point data for the target point.
|===

==== `clearTargets()`

This function allows you to remove all targets from the target list.

==== `TargetPoint[] getTargets()`

This function returns an array of all target points in the target list.

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|TargetPoint[]
|TargetPoint[]
|An array of target point data of all target points in the target list.
|===

==== `setTarget(TargetPoint[] targets)`

This function removes all target points from the target list and replaces them with the given target point list.

Return Values::
+
[cols="1,1,4a"]
|===
|Name |Type |Description

|targets
|TargetPoint[]
|An array of target point data of all target points you want now to add to the freshly cleared target list.
|===

=== Properties

==== `number speed (readonly)`

The current forward speed of the vehicle.

==== `number burnRatio (readonly)`

The current fuel burnRatio of the vehicles engine.

==== `int wheelsOnGround (readonly)`

The number of wheels currently on the ground.

==== `bool hasFuel (readonly)`

True if the vehicle has currently fuel to run the engine.

==== `bool isInAir (readonly)`

True if the vehicle is currently in the air.

==== `bool wantsToMove (readonly)`

True if the vehicle currently wants to move.

==== `bool isDrifting (readonly)`

True if the vehcile is currently drifting.

== TargetPoint

This **structure** holds information about a wheeled vehicles target points (blue path points when you record a vehicle track) used in the target list.
It holds infromation like position and rotation of such a target point aswell as the expected vehicle
speed and amount of time the vehicle will wait when it reaches the target.

=== Implicit Construction

The structure can be implicitly create by a table that contains the exact same fields like the structure. (names and data types)

=== Fields

==== `number x`

The x coordinate of were the target is located.

==== `number y`

The y coordinate of were the target is located.

==== `number z`

The z coordinate of were the target is located.

==== `number pitch`

The pitch component of the targets rotation.

==== `number yaw`

The yaw component of the targets rotation.

==== `number roll`

The roll component of the targets rotation.

==== `number speed`

The expected speed of the vehicle when it reaches the target.

==== `number wait`

How long the vehicle should wait at this target, until it continues to the next target, when it reaches it.



include::partial$api_footer.adoc[]