= Basic Concept
:description: The basic concepts of FicsIt-Networks like network setup and interaction.

== Network Connector

A Network Connector is simply a point of a building were you can connect a network cable to and so, connect multiple different network components with eachother.

The Network Connector is also a Network Component itself.

== Network Component

A Network Component is anything that is connected to the network and can provide a interface for interactions to the network.

Network Components can be identified individually by their ID which is a guid (a implementation of UUID)

Example::
+
```
0123456789abcdef0123456789abcdef
```

Network Components can have a nick, which is a list of custom names seperated by spaces allowing you to group and name your network components.
Nick filters are then used to check if a network component has specific nicknames.

Example::
+
[source,Lua]
----
nick1 = "Test Power" -- nick1 with names "Test" and "Power"
nick2 = "Power" -- nick2 with name "Power"

filter1 = "Power" -- nick filter maches nick1 and nick2
filter2 = "Test" -- nick filter maches only nick1
filter3 = "Test Power" -- nick filter maches only nick1
filter4 = "Power Nice" -- nick filter maches noone
filter5 = "" -- nick filter maches every component (also components with no nick)
----

== Reflection-System

The Reflection System provided by FicsIt-Networks,
provides users and developers a abstract interface with game functionality.
Compared to the reflection system provided by unreal engine,
this reflection system additional holds metadata like localized display names and descriptions,
for all the different pieces in the system.

The system also only allows to access "reasonable" functions and properties,
so even when you have full access to this reflection system,
you can not use it to cheat, like creating items out of nowhere.

The reflection system provides a couple of description objects:

- Base
+
Is the base for all following things, providing some basic information like
the internal name, which is used for referencing and f.e. in Lua code,
the display name which is localized and used to show a good name to the user
and a localized description.
- Struct
+
Holds additionally a list of functions and properties this type has.
Is used to describe a structure type.
- Class
+
Bases of `Struct` and additional contains a list of signals this class has.
Is used to describe object types.

- Property
+
Holds information about function parameters, signal parameters or simple attributes.
It also stores the network value type, and bit flag register with information about
allowed runtime environments, read only mode, accessibility and such.

- Function
+
Holds information about a function you can call.
This is done by additionally holding a list of input and output parameters of this function.
As well as holding a bit flag register with information about
allowed runtime environments, accessibility and such.

- Signal
+
Holds information about a push signal a object might emit.
Provides a list of parameters this signal has and if it has a variable amount of parameters.

The reflection system utilizes multiple sources to generate the interface.
One is simply using the unreal reflection system and searching for special functions and properties (see xref::ModIntegration.adoc[Mod Integration] for more details).
Another is a static registry that matches existing types, like objects from Satisfactory (like a constructor), with reflection data.

You can look up all this information with the reflection viewer,
which you can open f.e. with the network manager.
