// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGAttentionPingActor.h"

AFGAttentionPingActor::AFGAttentionPingActor(){ }
void AFGAttentionPingActor::BeginPlay(){ }
void AFGAttentionPingActor::GetLifetimeReplicatedProps( TArray<FLifetimeProperty>& OutLifetimeProps) const{ }
void AFGAttentionPingActor::SetPlayerSlotIdx( int32 slotIdx){ }
void AFGAttentionPingActor::OnRep_PlayerSlotIdx(){ }
