= Factory
:table-caption!:

[cols="1,5a",separator="!"]
!===
! Parent
! xref:/reflection/classes/Buildable.adoc[Buildable]
!===

The base class of most machines you can build.

// tag::interface[]

== Properties

// tag::func-cycleTime-title[]
=== `cycleTime` : Float
// tag::func-cycleTime[]

The time that passes till one production cycle is finsihed.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Cycle Time
!===
====
// end::func-cycleTime[]
// end::func-cycleTime-title[]
// tag::func-maxPotential-title[]
=== `maxPotential` : Float
// tag::func-maxPotential[]

The maximum potential this factory can be set to.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Max Potential
!===
====
// end::func-maxPotential[]
// end::func-maxPotential-title[]
// tag::func-minPotential-title[]
=== `minPotential` : Float
// tag::func-minPotential[]

The minimum potential this factory needs to be set to.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Min Potential
!===
====
// end::func-minPotential[]
// end::func-minPotential-title[]
// tag::func-potential-title[]
=== `potential` : Float
// tag::func-potential[]

The potential this factory is currently set to. (the overclock value)
 0 = 0%, 1 = 100%

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Potential
!===
====
// end::func-potential[]
// end::func-potential-title[]
// tag::func-powerConsumProducing-title[]
=== `powerConsumProducing` : Float
// tag::func-powerConsumProducing[]

The power consumption when producing.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Producing Power Consumption
!===
====
// end::func-powerConsumProducing[]
// end::func-powerConsumProducing-title[]
// tag::func-productivity-title[]
=== `productivity` : Float
// tag::func-productivity[]

The productivity of this factory.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Productivity
!===
====
// end::func-productivity[]
// end::func-productivity-title[]
// tag::func-progress-title[]
=== `progress` : Float
// tag::func-progress[]

The current production progress of the current production cycle.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Progress
!===
====
// end::func-progress[]
// end::func-progress-title[]
// tag::func-standby-title[]
=== `standby` : Bool
// tag::func-standby[]

True if the factory is in standby.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Standby
!===
====
// end::func-standby[]
// end::func-standby-title[]

// end::interface[]

