= Indicator Pole
:table-caption!:



// tag::interface[]

== Functions

// tag::func-getColor-title[]
=== `getColor` () -> (`r` : Float, `g` : Float, `b` : Float, `e` : Float)
// tag::func-getColor[]

Allows to get the color and light intensity of the indicator lamp.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Get Color
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Red* `r`
! Float
! The red part of the color in which the light glows. (0.0 - 1.0)

! *Green* `g`
! Float
! The green part of the color in which the light glows. (0.0 - 1.0)

! *Blue* `b`
! Float
! The blue part of the color in which the light glows. (0.0 - 1.0)

! *Emissive* `e`
! Float
! The light intensity of the pole. (0.0 - 5.0)
!===

====
// end::func-getColor[]
// end::func-getColor-title[]
// tag::func-getTopPole-title[]
=== `getTopPole` () -> `topPole` : Object<xref:/reflection/classes/IndicatorPole.adoc[IndicatorPole]>
// tag::func-getTopPole[]

Allows to get the pole placed on top of this pole.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Get Top Pole
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Top Pole* `topPole`
! Object<xref:/reflection/classes/IndicatorPole.adoc[IndicatorPole]>
! The pole placed on top of this pole.
!===

====
// end::func-getTopPole[]
// end::func-getTopPole-title[]
// tag::func-setColor-title[]
=== `setColor` (`r` : Float, `g` : Float, `b` : Float, `e` : Float)
// tag::func-setColor[]

Allows to change the color and light intensity of the indicator lamp.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#bb2828'><i>RuntimeAsync</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Set Color
!===

.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Red* `r`
! Float
! The red part of the color in which the light glows. (0.0 - 1.0)

! *Green* `g`
! Float
! The green part of the color in which the light glows. (0.0 - 1.0)

! *Blue* `b`
! Float
! The blue part of the color in which the light glows. (0.0 - 1.0)

! *Emissive* `e`
! Float
! The light intensity of the pole. (0.0 - 5.0)
!===

====
// end::func-setColor[]
// end::func-setColor-title[]
// tag::func-getBottomPole-title[]
=== `getBottomPole` () -> `ReturnValue` : Object<xref:/reflection/classes/IndicatorPole.adoc[IndicatorPole]>
// tag::func-getBottomPole[]



[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! getBottomPole
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *ReturnValue* `ReturnValue`
! Object<xref:/reflection/classes/IndicatorPole.adoc[IndicatorPole]>
! 
!===

====
// end::func-getBottomPole[]
// end::func-getBottomPole-title[]

== Signals

=== `ColorChanged` (_Float_ *Red* `r`, _Float_ *Green* `g`, _Float_ *Blue* `b`, _Float_ *Emissive* `e`)

Triggers when the color of the indicator pole changes.

[%collapsible]
====
.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Red* `r`
! Float
! The red part of the color in which the light glows. (0.0 - 1.0)

! *Green* `g`
! Float
! The green part of the color in which the light glows. (0.0 - 1.0)

! *Blue* `b`
! Float
! The blue part of the color in which the light glows. (0.0 - 1.0)

! *Emissive* `e`
! Float
! The light intensity of the pole. (0.0 - 5.0)
!===
====


// end::interface[]

