= Item Type
:table-caption!:

The type of an item (iron plate, iron rod, leaves)

// tag::interface[]

== Properties

// tag::func-canBeDiscarded-title[]
=== `canBeDiscarded` : Bool
// tag::func-canBeDiscarded[]

True if this item can be discarded.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>ClassProp</i></span>+++

! Display Name ! Can be Discarded
!===
====
// end::func-canBeDiscarded[]
// end::func-canBeDiscarded-title[]
// tag::func-category-title[]
=== `category` : Class<xref:/reflection/classes/ItemCategory.adoc[ItemCategory]>
// tag::func-category[]

The category in which this item is in.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>ClassProp</i></span>+++

! Display Name ! Category
!===
====
// end::func-category[]
// end::func-category-title[]
// tag::func-description-title[]
=== `description` : String
// tag::func-description[]

The description of this item.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>ClassProp</i></span>+++

! Display Name ! Description
!===
====
// end::func-description[]
// end::func-description-title[]
// tag::func-energy-title[]
=== `energy` : Float
// tag::func-energy[]

How much energy this resource provides if used as fuel.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>ClassProp</i></span>+++

! Display Name ! Energy
!===
====
// end::func-energy[]
// end::func-energy-title[]
// tag::func-fluidColor-title[]
=== `fluidColor` : Struct<xref:/reflection/structs/Color.adoc[Color]>
// tag::func-fluidColor[]

The color of this fluid.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>ClassProp</i></span>+++

! Display Name ! Fluid Color
!===
====
// end::func-fluidColor[]
// end::func-fluidColor-title[]
// tag::func-form-title[]
=== `form` : Int
// tag::func-form[]

The matter state of this resource.
1: Solid
2: Liquid
3: Gas
4: Heat

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>ClassProp</i></span>+++

! Display Name ! Form
!===
====
// end::func-form[]
// end::func-form-title[]
// tag::func-max-title[]
=== `max` : Int
// tag::func-max[]

The maximum stack size of this item.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>ClassProp</i></span>+++

! Display Name ! Max
!===
====
// end::func-max[]
// end::func-max-title[]
// tag::func-name-title[]
=== `name` : String
// tag::func-name[]

The name of the item.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>ClassProp</i></span>+++

! Display Name ! Name
!===
====
// end::func-name[]
// end::func-name-title[]
// tag::func-radioactiveDecay-title[]
=== `radioactiveDecay` : Float
// tag::func-radioactiveDecay[]

The amount of radiation this item radiates.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>ClassProp</i></span>+++

! Display Name ! Radioactive Decay
!===
====
// end::func-radioactiveDecay[]
// end::func-radioactiveDecay-title[]

// end::interface[]

