= Large Micro Display Module
:table-caption!:

[cols="1,5a",separator="!"]
!===
! Parent
! xref:/reflection/classes/Buildable.adoc[FINModuleBase]
!===

Provides a relatively small text only display for Control Panels. 
Text height is fixed, but text is squeezed to fit horizontally.

// tag::interface[]

== Functions

// tag::func-setText-title[]
=== `setText` (`text` : String)
// tag::func-setText[]

Sets the text to be displayed on this micro display

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Set Text
!===

.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Text* `text`
! String
! The new text to display
!===

====
// end::func-setText[]
// end::func-setText-title[]
// tag::func-setColor-title[]
=== `setColor` (`Red` : Float, `Green` : Float, `Blue` : Float, `Emit` : Float)
// tag::func-setColor[]



[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! setColor
!===

.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Red* `Red`
! Float
! 

! *Green* `Green`
! Float
! 

! *Blue* `Blue`
! Float
! 

! *Emit* `Emit`
! Float
! 
!===

====
// end::func-setColor[]
// end::func-setColor-title[]

// end::interface[]

