= Light Source
:table-caption!:

[cols="1,5a",separator="!"]
!===
! Parent
! xref:/reflection/classes/CircuitBridge.adoc[FGBuildableControlPanelHost]
!===

A control panel to configure multiple lights at once.

// tag::interface[]

== Properties

// tag::func-colorSlot-title[]
=== `colorSlot` : Int
// tag::func-colorSlot[]

The color slot the lights should use.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Color Slot
!===
====
// end::func-colorSlot[]
// end::func-colorSlot-title[]
// tag::func-intensity-title[]
=== `intensity` : Float
// tag::func-intensity[]

The intensity of the lights.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Intensity
!===
====
// end::func-intensity[]
// end::func-intensity-title[]
// tag::func-isLightEnabled-title[]
=== `isLightEnabled` : Bool
// tag::func-isLightEnabled[]

True if the lights should be enabled

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Is Light Enabled
!===
====
// end::func-isLightEnabled[]
// end::func-isLightEnabled-title[]
// tag::func-isTimeOfDayAware-title[]
=== `isTimeOfDayAware` : Bool
// tag::func-isTimeOfDayAware[]

True if the lights should automatically turn on and off depending on the time of the day.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Is Time of Day Aware
!===
====
// end::func-isTimeOfDayAware[]
// end::func-isTimeOfDayAware-title[]

== Functions

// tag::func-setColorFromSlot-title[]
=== `setColorFromSlot` (`slot` : Int, `color` : Struct<xref:/reflection/structs/Color.adoc[Color]>)
// tag::func-setColorFromSlot[]

Allows to update the light color that is referenced by the given slot.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Set Color from Slot
!===

.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Slot* `slot`
! Int
! The slot you want to update the referencing color for.

! *Color* `color`
! Struct<xref:/reflection/structs/Color.adoc[Color]>
! The color this slot should now reference.
!===

====
// end::func-setColorFromSlot[]
// end::func-setColorFromSlot-title[]

// end::interface[]

