= ModulePanel
:table-caption!:

Enclosure for 1 command points

// tag::interface[]

== Functions

// tag::func-getModules-title[]
=== `getModules` () -> `modules` : Array<Object<xref:/reflection/classes/Object.adoc[Object]>>
// tag::func-getModules[]

Returns all modules placed on the panel.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Get All Modules
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Modules* `modules`
! Array<Object<xref:/reflection/classes/Object.adoc[Object]>>
! All the modules placed on the panel.
!===

====
// end::func-getModules[]
// end::func-getModules-title[]
// tag::func-getModule-title[]
=== `getModule` (`x` : Int, `y` : Int) -> `module` : Object<xref:/reflection/classes/Actor.adoc[Actor]>
// tag::func-getModule[]

Returns the module placed at the given location on the panel.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Get Module
!===

.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *X* `x`
! Int
! The x position of the command point, starting from the non-cable end. Indexing starts at 0.

! *Y* `y`
! Int
! The y position  of the command point, starting from the non-cable end. Indexing starts at 0.
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Module* `module`
! Object<xref:/reflection/classes/Actor.adoc[Actor]>
! The module you want to get. Null if no module was placed.
!===

====
// end::func-getModule[]
// end::func-getModule-title[]
// tag::func-getXModule-title[]
=== `getXModule` (`X` : Int) -> `Module` : Object<xref:/reflection/classes/Actor.adoc[Actor]>
// tag::func-getXModule[]



[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! getXModule
!===

.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *X* `X`
! Int
! 
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Module* `Module`
! Object<xref:/reflection/classes/Actor.adoc[Actor]>
! 
!===

====
// end::func-getXModule[]
// end::func-getXModule-title[]
// tag::func-getYModule-title[]
=== `getYModule` (`Y` : Int) -> `Module` : Object<xref:/reflection/classes/Actor.adoc[Actor]>
// tag::func-getYModule[]



[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! getYModule
!===

.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Y* `Y`
! Int
! 
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Module* `Module`
! Object<xref:/reflection/classes/Actor.adoc[Actor]>
! 
!===

====
// end::func-getYModule[]
// end::func-getYModule-title[]

// end::interface[]

