= Potentiometer Module
:table-caption!:

This Potentiometer Module allows for input of a fixed value range and fires a signal with the new value each time the internal counter changes.

// tag::interface[]

== Properties

// tag::func-enabled-title[]
=== `enabled` : Bool
// tag::func-enabled[]

Sets wheter to accept input on this encoder or not. True means accept input, false means to igore input

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Enabled
!===
====
// end::func-enabled[]
// end::func-enabled-title[]
// tag::func-max-title[]
=== `max` : Int
// tag::func-max[]

The maximum  value for this potentiometer

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Maximum
!===
====
// end::func-max[]
// end::func-max-title[]
// tag::func-min-title[]
=== `min` : Int
// tag::func-min[]

The minimum value for this potentiometer

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Minimum
!===
====
// end::func-min[]
// end::func-min-title[]
// tag::func-value-title[]
=== `value` : Int
// tag::func-value[]

The current value of this potentiometer. Setting this will change the internal value.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Value
!===
====
// end::func-value[]
// end::func-value-title[]

== Functions

// tag::func-setColor-title[]
=== `setColor` (`red` : Float, `green` : Float, `blue` : Float, `Emit` : Float)
// tag::func-setColor[]



[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! setColor
!===

.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *red* `red`
! Float
! 

! *green* `green`
! Float
! 

! *blue* `blue`
! Float
! 

! *Emit* `Emit`
! Float
! 
!===

====
// end::func-setColor[]
// end::func-setColor-title[]

== Signals

=== `valueChanged` (_Int_ *Value* `value`)

Signal fired when this potentiometers value changes by user interaction.

[%collapsible]
====
.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Value* `value`
! Int
! The new value of this potentiometer
!===
====


// end::interface[]

