= Potentiometer With Display Module
:table-caption!:

[cols="1,5a",separator="!"]
!===
! Parent
! xref:/reflection/classes/Buildable.adoc[FINModuleBase]
!===

This Potentiometer Module allows for input of a fixed value range and fires a signal with the new value each time the internal counter changes. This version has a readout display on it.

// tag::interface[]

== Properties

// tag::func-autovalue-title[]
=== `autovalue` : Bool
// tag::func-autovalue[]

This sets whether or not to automatically update the display text to the potentiometer value or to use custom text. Default is true. All setText calls will be ignored if true.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Auto Value
!===
====
// end::func-autovalue[]
// end::func-autovalue-title[]
// tag::func-enabled-title[]
=== `enabled` : Bool
// tag::func-enabled[]

Sets wheter to accept input on this encoder or not. True means accept input, false means to igore input

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Enabled
!===
====
// end::func-enabled[]
// end::func-enabled-title[]
// tag::func-max-title[]
=== `max` : Int
// tag::func-max[]

The maximum  value for this potentiometer

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Maximum
!===
====
// end::func-max[]
// end::func-max-title[]
// tag::func-min-title[]
=== `min` : Int
// tag::func-min[]

The minimum value for this potentiometer

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Minimum
!===
====
// end::func-min[]
// end::func-min-title[]
// tag::func-value-title[]
=== `value` : Int
// tag::func-value[]

The current value of this potentiometer. Setting this will change the internal value.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Value
!===
====
// end::func-value[]
// end::func-value-title[]

== Functions

// tag::func-setText-title[]
=== `setText` (`text` : String)
// tag::func-setText[]

Sets the text to be displayed on this micro display

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Set Text
!===

.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Text* `text`
! String
! The new text to display
!===

====
// end::func-setText[]
// end::func-setText-title[]
// tag::func-setColor-title[]
=== `setColor` (`Red` : Float, `Green` : Float, `Blue` : Float, `Emit` : Float)
// tag::func-setColor[]



[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! setColor
!===

.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Red* `Red`
! Float
! 

! *Green* `Green`
! Float
! 

! *Blue* `Blue`
! Float
! 

! *Emit* `Emit`
! Float
! 
!===

====
// end::func-setColor[]
// end::func-setColor-title[]

== Signals

=== `value` (_Int_ *Value* `value`)

Signal fired when this potentiometers value changes by user interaction.

[%collapsible]
====
.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Value* `value`
! Int
! The new value of this potentiometer
!===
====


// end::interface[]

