= Pushbutton Module
:table-caption!:

[cols="1,5a",separator="!"]
!===
! Parent
! xref:/reflection/classes/Buildable.adoc[FINModuleBase]
!===

This Button Module for modular I/O Panels can have different knob color and brightnesses and you can use them to trigger specific programmed events.

Use the Ficsit Label Marker to change the text and foreground color of the button.

// tag::interface[]

== Properties

// tag::func-enabled-title[]
=== `enabled` : Bool
// tag::func-enabled[]

Sets whether to accept input on this encoder or not. True means accept input, false means to igore input

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Enabled
!===
====
// end::func-enabled[]
// end::func-enabled-title[]
// tag::func-operationalMode-title[]
=== `operationalMode` : Int
// tag::func-operationalMode[]

Sets the mode this button works in. Both in terms of signals and how it works.

0 = Single Signal, Basic mode. This mode is just a simple push button with a single Trigger signal
1 = Double Signal. This mode gives a trigger signal on press and one on release. The first boolean parameter determines if it was a press (true) or release (false) event 
2 = Double Signal with Latched function. This is like 1 but the button stays pressed until the next trigger.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Operational Mode
!===
====
// end::func-operationalMode[]
// end::func-operationalMode-title[]
// tag::func-state-title[]
=== `state` : Bool
// tag::func-state[]

Returns whether this button is currently being pressed or not. 
This is only useful when the operationalMode is set to either of the Double modes.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! State
!===
====
// end::func-state[]
// end::func-state-title[]

== Functions

// tag::func-Trigger-title[]
=== `Trigger` ()
// tag::func-Trigger[]

Triggers a button press by code.

THIS FUNCTION HAS NOT YET BEEN IMPLEMENTED

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Trigger
!===

====
// end::func-Trigger[]
// end::func-Trigger-title[]
// tag::func-setColor-title[]
=== `setColor` (`Red` : Float, `Green` : Float, `Blue` : Float, `Emit` : Float)
// tag::func-setColor[]



[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! setColor
!===

.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Red* `Red`
! Float
! 

! *Green* `Green`
! Float
! 

! *Blue* `Blue`
! Float
! 

! *Emit* `Emit`
! Float
! 
!===

====
// end::func-setColor[]
// end::func-setColor-title[]

== Signals

=== `Trigger` (_Bool_ *State* `state`)

Triggers when the button gets acted on.

[%collapsible]
====
.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *State* `state`
! Bool
! If operationalMode is 0, always set to true.
  If operationalMode is 1 or 2, true if pressed, false if depressed.
!===
====


// end::interface[]

