= Pushbutton Module
:table-caption!:

[cols="1,5a",separator="!"]
!===
! Parent
! xref:/reflection/classes/Buildable.adoc[FINModuleBase]
!===

This Button Module for modular I/O Panels can have different knob color and brightnesses and you can use them to trigger specific programmed events.

Use the Ficsit Label Marker to change the text and foreground color of the button.

// tag::interface[]

== Properties

// tag::func-enabled-title[]
=== `enabled` : Bool
// tag::func-enabled[]

Sets wheter to accept input on this encoder or not. True means accept input, false means to igore input

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Enabled
!===
====
// end::func-enabled[]
// end::func-enabled-title[]

== Functions

// tag::func-Trigger-title[]
=== `Trigger` ()
// tag::func-Trigger[]

Triggers a button press by code.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Trigger
!===

====
// end::func-Trigger[]
// end::func-Trigger-title[]
// tag::func-setColor-title[]
=== `setColor` (`Red` : Float, `Green` : Float, `Blue` : Float, `Emit` : Float)
// tag::func-setColor[]



[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! setColor
!===

.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Red* `Red`
! Float
! 

! *Green* `Green`
! Float
! 

! *Blue* `Blue`
! Float
! 

! *Emit* `Emit`
! Float
! 
!===

====
// end::func-setColor[]
// end::func-setColor-title[]

== Signals

=== `Trigger` ()

Triggers when the button gets pressed.


// end::interface[]

