= Railroad Vehicle
:table-caption!:

The base class for any vehicle that drives on train tracks.

// tag::interface[]

== Properties

// tag::func-isDocked-title[]
=== `isDocked` : Bool
// tag::func-isDocked[]

True if this vehicle is currently docked to a platform.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Is Docked
!===
====
// end::func-isDocked[]
// end::func-isDocked-title[]
// tag::func-isReversed-title[]
=== `isReversed` : Bool
// tag::func-isReversed[]

True if the vheicle is placed reversed on the track.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Is Reversed
!===
====
// end::func-isReversed[]
// end::func-isReversed-title[]
// tag::func-length-title[]
=== `length` : Float
// tag::func-length[]

The length of this vehicle on the track.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Length
!===
====
// end::func-length[]
// end::func-length-title[]

== Functions

// tag::func-getCoupled-title[]
=== `getCoupled` (`coupler` : Int) -> `coupled` : Trace<xref:/reflection/classes/RailroadVehicle.adoc[RailroadVehicle]>
// tag::func-getCoupled[]

Allows to get the coupled vehicle at the given coupler.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Get Coupled
!===

.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Coupler* `coupler`
! Int
! The Coupler you want to get the car from. 0 = Front, 1 = Back
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Coupled* `coupled`
! Trace<xref:/reflection/classes/RailroadVehicle.adoc[RailroadVehicle]>
! The coupled car of the given coupler is coupled to another car.
!===

====
// end::func-getCoupled[]
// end::func-getCoupled-title[]
// tag::func-getMovement-title[]
=== `getMovement` () -> `movement` : Trace<xref:/reflection/classes/RailroadVehicleMovement.adoc[RailroadVehicleMovement]>
// tag::func-getMovement[]

Returns the vehicle movement of this vehicle.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Get Movement
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Movement* `movement`
! Trace<xref:/reflection/classes/RailroadVehicleMovement.adoc[RailroadVehicleMovement]>
! The movement of this vehicle.
!===

====
// end::func-getMovement[]
// end::func-getMovement-title[]
// tag::func-getTrackGraph-title[]
=== `getTrackGraph` () -> `track` : Struct<xref:/reflection/structs/TrackGraph.adoc[TrackGraph]>
// tag::func-getTrackGraph[]

Returns the track graph of which this vehicle is part of.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Get Track Graph
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Track* `track`
! Struct<xref:/reflection/structs/TrackGraph.adoc[TrackGraph]>
! The track graph of which this vehicle is part of.
!===

====
// end::func-getTrackGraph[]
// end::func-getTrackGraph-title[]
// tag::func-getTrackPos-title[]
=== `getTrackPos` () -> (`track` : Trace<xref:/reflection/classes/RailroadTrack.adoc[RailroadTrack]>, `offset` : Float, `forward` : Float)
// tag::func-getTrackPos[]

Returns the track pos at which this vehicle is.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Get Track Pos
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Track* `track`
! Trace<xref:/reflection/classes/RailroadTrack.adoc[RailroadTrack]>
! The track the track pos points to.

! *Offset* `offset`
! Float
! The offset of the track pos.

! *Forward* `forward`
! Float
! The forward direction of the track pos. 1 = with the track direction, -1 = against the track direction
!===

====
// end::func-getTrackPos[]
// end::func-getTrackPos-title[]
// tag::func-getTrain-title[]
=== `getTrain` () -> `train` : Trace<xref:/reflection/classes/Train.adoc[Train]>
// tag::func-getTrain[]

Returns the train of which this vehicle is part of.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Get Train
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Train* `train`
! Trace<xref:/reflection/classes/Train.adoc[Train]>
! The train of which this vehicle is part of
!===

====
// end::func-getTrain[]
// end::func-getTrain-title[]
// tag::func-isCoupled-title[]
=== `isCoupled` (`coupler` : Int) -> `coupled` : Bool
// tag::func-isCoupled[]

Allows to check if the given coupler is coupled to another car.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Is Coupled
!===

.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Coupler* `coupler`
! Int
! The Coupler you want to check. 0 = Front, 1 = Back
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Coupled* `coupled`
! Bool
! True of the give coupler is coupled to another car.
!===

====
// end::func-isCoupled[]
// end::func-isCoupled-title[]

// end::interface[]

