= Resource Sink
:table-caption!:

The resource sink, also known a A.W.E.S.O.M.E Sink

// tag::interface[]

== Properties

// tag::func-couponProgress-title[]
=== `couponProgress` : Float
// tag::func-couponProgress[]

The percentage of the progress for the next coupon.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Coupon Progress
!===
====
// end::func-couponProgress[]
// end::func-couponProgress-title[]
// tag::func-numCoupons-title[]
=== `numCoupons` : Int
// tag::func-numCoupons[]

The number of available coupons to print.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Num Coupons
!===
====
// end::func-numCoupons[]
// end::func-numCoupons-title[]
// tag::func-numPoints-title[]
=== `numPoints` : Int
// tag::func-numPoints[]

The number of available points.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Num Points
!===
====
// end::func-numPoints[]
// end::func-numPoints-title[]
// tag::func-numPointsToNextCoupon-title[]
=== `numPointsToNextCoupon` : Int
// tag::func-numPointsToNextCoupon[]

The number of needed points for the next coupon.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Num Points To Next Coupon
!===
====
// end::func-numPointsToNextCoupon[]
// end::func-numPointsToNextCoupon-title[]

// end::interface[]

