= Sizeable Module Panel
:table-caption!:

[cols="1,5a",separator="!"]
!===
! Parent
! xref:/reflection/classes/Buildable.adoc[FINSizeablePanel]
!===

This panel allows for dynamic sizeing. For placing on walls.

// tag::interface[]

== Properties

// tag::func-height-title[]
=== `height` : Int
// tag::func-height[]

The Height of this panel in modules

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Height
!===
====
// end::func-height[]
// end::func-height-title[]
// tag::func-width-title[]
=== `width` : Int
// tag::func-width[]

The Width of this panel in modules

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Width
!===
====
// end::func-width[]
// end::func-width-title[]

== Functions

// tag::func-getModules-title[]
=== `getModules` () -> `modules` : Array<Object<xref:/reflection/classes/Object.adoc[Object]>>
// tag::func-getModules[]

Returns all modules placed on the panel.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Get All Modules
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Modules* `modules`
! Array<Object<xref:/reflection/classes/Object.adoc[Object]>>
! All the modules placed on the panel.
!===

====
// end::func-getModules[]
// end::func-getModules-title[]
// tag::func-getModule-title[]
=== `getModule` (`x` : Int, `y` : Int) -> `module` : Object<xref:/reflection/classes/Actor.adoc[Actor]>
// tag::func-getModule[]

Returns the module placed at the given location on the panel.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Get Module
!===

.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *X* `x`
! Int
! The x position of the command point, starting from the non-cable end. Indexing starts at 0.

! *Y* `y`
! Int
! The y position  of the command point, starting from the non-cable end. Indexing starts at 0.
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Module* `module`
! Object<xref:/reflection/classes/Actor.adoc[Actor]>
! The module you want to get. Null if no module was placed.
!===

====
// end::func-getModule[]
// end::func-getModule-title[]

// end::interface[]

