= Speaker-Pole
:table-caption!:

The FicsIt-Networks speaker pole is a network component which allows you to use one more sense of the pioneers to give commands to them or to just make ambient better.

The speaker pole can play sound files located in the Computer Folder "/Sounds" in your Satisfactory Save-Games-Folder. The FicsIt-Networks speaker pole is only able to play .ogg files cause FicsIt Inc. has the opinion other file formates are useless.

// tag::interface[]

== Functions

// tag::func-getRange-title[]
=== `getRange` () -> `Range` : Float
// tag::func-getRange[]



[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! getRange
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Range* `Range`
! Float
! 
!===

====
// end::func-getRange[]
// end::func-getRange-title[]
// tag::func-getVolume-title[]
=== `getVolume` () -> `Volume` : Float
// tag::func-getVolume[]



[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! getVolume
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Volume* `Volume`
! Float
! 
!===

====
// end::func-getVolume[]
// end::func-getVolume-title[]
// tag::func-setRange-title[]
=== `setRange` (`Range` : Float)
// tag::func-setRange[]



[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! setRange
!===

.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Range* `Range`
! Float
! 
!===

====
// end::func-setRange[]
// end::func-setRange-title[]
// tag::func-setVolume-title[]
=== `setVolume` (`Volume` : Float)
// tag::func-setVolume[]



[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! setVolume
!===

.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Volume* `Volume`
! Float
! 
!===

====
// end::func-setVolume[]
// end::func-setVolume-title[]

== Signals

=== `SpeakerSetting` (_Int_ *setting* `setting`, _Float_ *New* `New`, _Float_ *Old* `Old`)



[%collapsible]
====
.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *setting* `setting`
! Int
! 

! *New* `New`
! Float
! 

! *Old* `Old`
! Float
! 
!===
====


// end::interface[]

