= Train
:table-caption!:

[cols="1,5a",separator="!"]
!===
! Parent
! xref:/reflection/classes/Actor.adoc[Actor]
!===

This class holds information and references about a trains (a collection of multiple railroad vehicles) and its timetable f.e.

// tag::interface[]

== Properties

// tag::func-dockState-title[]
=== `dockState` : Int
// tag::func-dockState[]

The current docking state of the train.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Dock State
!===
====
// end::func-dockState[]
// end::func-dockState-title[]
// tag::func-hasTimeTable-title[]
=== `hasTimeTable` : Bool
// tag::func-hasTimeTable[]

True if the train has currently a time table.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Has Time Table
!===
====
// end::func-hasTimeTable[]
// end::func-hasTimeTable-title[]
// tag::func-isDocked-title[]
=== `isDocked` : Bool
// tag::func-isDocked[]

True if the train is currently docked.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Is Docked
!===
====
// end::func-isDocked[]
// end::func-isDocked-title[]
// tag::func-isPlayerDriven-title[]
=== `isPlayerDriven` : Bool
// tag::func-isPlayerDriven[]

True if the train is currently player driven.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Is Player Driven
!===
====
// end::func-isPlayerDriven[]
// end::func-isPlayerDriven-title[]
// tag::func-isSelfDriving-title[]
=== `isSelfDriving` : Bool
// tag::func-isSelfDriving[]

True if the train is currently self driving.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Is Self Driving
!===
====
// end::func-isSelfDriving[]
// end::func-isSelfDriving-title[]
// tag::func-selfDrivingError-title[]
=== `selfDrivingError` : Int
// tag::func-selfDrivingError[]

The last self driving error.
0 = No Error
1 = No Power
2 = No Time Table
3 = Invalid Next Stop
4 = Invalid Locomotive Placement
5 = No Path

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags ! +++<span style='color:#e59445'><i>ReadOnly</i></span> <span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span>+++

! Display Name ! Self Driving Error
!===
====
// end::func-selfDrivingError[]
// end::func-selfDrivingError-title[]

== Functions

// tag::func-dock-title[]
=== `dock` ()
// tag::func-dock[]

Trys to dock the train to the station it is currently at.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Dock
!===

====
// end::func-dock[]
// end::func-dock-title[]
// tag::func-getFirst-title[]
=== `getFirst` () -> `first` : Trace<xref:/reflection/classes/RailroadVehicle.adoc[RailroadVehicle]>
// tag::func-getFirst[]

Returns the first railroad vehicle that is part of this train.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Get First
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *First* `first`
! Trace<xref:/reflection/classes/RailroadVehicle.adoc[RailroadVehicle]>
! The first railroad vehicle that is part of this train.
!===

====
// end::func-getFirst[]
// end::func-getFirst-title[]
// tag::func-getLast-title[]
=== `getLast` () -> `last` : Trace<xref:/reflection/classes/RailroadVehicle.adoc[RailroadVehicle]>
// tag::func-getLast[]

Returns the last railroad vehicle that is part of this train.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Get Last
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Last* `last`
! Trace<xref:/reflection/classes/RailroadVehicle.adoc[RailroadVehicle]>
! The last railroad vehicle that is part of this train.
!===

====
// end::func-getLast[]
// end::func-getLast-title[]
// tag::func-getMaster-title[]
=== `getMaster` () -> `master` : Trace<xref:/reflection/classes/RailroadVehicle.adoc[RailroadVehicle]>
// tag::func-getMaster[]

Returns the master locomotive that is part of this train.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Get Master
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Master* `master`
! Trace<xref:/reflection/classes/RailroadVehicle.adoc[RailroadVehicle]>
! The master locomotive of this train.
!===

====
// end::func-getMaster[]
// end::func-getMaster-title[]
// tag::func-getName-title[]
=== `getName` () -> `name` : String
// tag::func-getName[]

Returns the name of this train.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Get Name
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Name* `name`
! String
! The name of this train.
!===

====
// end::func-getName[]
// end::func-getName-title[]
// tag::func-getTimeTable-title[]
=== `getTimeTable` () -> `timeTable` : Trace<xref:/reflection/classes/TimeTable.adoc[TimeTable]>
// tag::func-getTimeTable[]

Returns the timetable of this train.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Get Time Table
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Time Table* `timeTable`
! Trace<xref:/reflection/classes/TimeTable.adoc[TimeTable]>
! The timetable of this train.
!===

====
// end::func-getTimeTable[]
// end::func-getTimeTable-title[]
// tag::func-getTrackGraph-title[]
=== `getTrackGraph` () -> `track` : Struct<xref:/reflection/structs/TrackGraph.adoc[TrackGraph]>
// tag::func-getTrackGraph[]

Returns the track graph of which this train is part of.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Get Track Graph
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Track* `track`
! Struct<xref:/reflection/structs/TrackGraph.adoc[TrackGraph]>
! The track graph of which this train is part of.
!===

====
// end::func-getTrackGraph[]
// end::func-getTrackGraph-title[]
// tag::func-getVehicles-title[]
=== `getVehicles` () -> `vehicles` : Array<Trace<xref:/reflection/classes/RailroadVehicle.adoc[RailroadVehicle]>>
// tag::func-getVehicles[]

Returns a list of all the vehicles this train has.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Get Vehicles
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Vehicles* `vehicles`
! Array<Trace<xref:/reflection/classes/RailroadVehicle.adoc[RailroadVehicle]>>
! A list of all the vehicles this train has.
!===

====
// end::func-getVehicles[]
// end::func-getVehicles-title[]
// tag::func-newTimeTable-title[]
=== `newTimeTable` () -> `timeTable` : Trace<xref:/reflection/classes/TimeTable.adoc[TimeTable]>
// tag::func-newTimeTable[]

Creates and returns a new timetable for this train.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! New Time Table
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Time Table* `timeTable`
! Trace<xref:/reflection/classes/TimeTable.adoc[TimeTable]>
! The new timetable for this train.
!===

====
// end::func-newTimeTable[]
// end::func-newTimeTable-title[]
// tag::func-setName-title[]
=== `setName` (`name` : String)
// tag::func-setName[]

Allows to set the name of this train.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Set Name
!===

.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Name* `name`
! String
! The new name of this trian.
!===

====
// end::func-setName[]
// end::func-setName-title[]
// tag::func-setSelfDriving-title[]
=== `setSelfDriving` (`selfDriving` : Bool)
// tag::func-setSelfDriving[]

Allows to set if the train should be self driving or not.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Set Self Driving
!===

.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Self Driving* `selfDriving`
! Bool
! True if the train should be self driving.
!===

====
// end::func-setSelfDriving[]
// end::func-setSelfDriving-title[]

== Signals

=== `SelfDrvingUpdate` (_Bool_ *Enabled* `enabled`)

Triggers when the self driving mode of the train changes

[%collapsible]
====
.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Enabled* `enabled`
! Bool
! True if the train is now self driving.
!===
====


// end::interface[]

