= Vehicle Scanner
:table-caption!:

[cols="1,5a",separator="!"]
!===
! Parent
! xref:/reflection/classes/Buildable.adoc[Buildable]
!===



// tag::interface[]

== Functions

// tag::func-getColor-title[]
=== `getColor` () -> (`r` : Float, `g` : Float, `b` : Float, `e` : Float)
// tag::func-getColor[]

Allows to get the color and light intensity of the scanner.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Get Color
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Red* `r`
! Float
! The red part of the color in which the scanner glows. (0.0 - 1.0)

! *Green* `g`
! Float
! The green part of the color in which the scanner glows. (0.0 - 1.0)

! *Blue* `b`
! Float
! The blue part of the color in which the scanner glows. (0.0 - 1.0)

! *Emissive* `e`
! Float
! The light intensity of the scanner. (0.0 - 5.0)
!===

====
// end::func-getColor[]
// end::func-getColor-title[]
// tag::func-getLastVehicle-title[]
=== `getLastVehicle` () -> `vehicle` : Object<xref:/reflection/classes/Vehicle.adoc[Vehicle]>
// tag::func-getLastVehicle[]

Returns the last vehicle that entered the scanner.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Get Last Vehicle
!===

.Return Values
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Vehicle* `vehicle`
! Object<xref:/reflection/classes/Vehicle.adoc[Vehicle]>
! The vehicle that entered the scanner. null if it has already left the scanner.
!===

====
// end::func-getLastVehicle[]
// end::func-getLastVehicle-title[]
// tag::func-setColor-title[]
=== `setColor` (`r` : Float, `g` : Float, `b` : Float, `e` : Float)
// tag::func-setColor[]

Allows to change the color and light intensity of the scanner.

[%collapsible]
====
[cols="1,5a",separator="!"]
!===
! Flags
! +++<span style='color:#bb2828'><i>RuntimeSync</i></span> <span style='color:#bb2828'><i>RuntimeParallel</i></span> <span style='color:#bb2828'><i>RuntimeAsync</i></span> <span style='color:#5dafc5'><i>MemberFunc</i></span>+++

! Display Name ! Set Color
!===

.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Red* `r`
! Float
! The red part of the color in which the scanner glows. (0.0 - 1.0)

! *Green* `g`
! Float
! The green part of the color in which the scanner glows. (0.0 - 1.0)

! *Blue* `b`
! Float
! The blue part of the color in which the scanner glows. (0.0 - 1.0)

! *Emissive* `e`
! Float
! The light intensity of the scanner. (0.0 - 5.0)
!===

====
// end::func-setColor[]
// end::func-setColor-title[]

== Signals

=== `OnVehicleEnter` (_Object<xref:/reflection/classes/Vehicle.adoc[Vehicle]>_ *Vehicle* `vehicle`)

Triggers when a vehicle enters the scanner.

[%collapsible]
====
.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Vehicle* `vehicle`
! Object<xref:/reflection/classes/Vehicle.adoc[Vehicle]>
! The vehicle that entered the scanner.
!===
====

=== `OnVehicleExit` (_Object<xref:/reflection/classes/Vehicle.adoc[Vehicle]>_ *Vehicle* `vehicle`)

Triggers when a vehicle leaves the scanner.

[%collapsible]
====
.Parameters
[%header,cols="1,1,4a",separator="!"]
!===
!Name !Type !Description

! *Vehicle* `vehicle`
! Object<xref:/reflection/classes/Vehicle.adoc[Vehicle]>
! The vehicle that left the scanner.
!===
====


// end::interface[]

