= Lua
:description: Lua is a very nice simple and easy to learn language and is just made for use in other programs as scripting interface. This is the most powerful tool you have in FicsIt-Networks.

The first and most powerful coding language implement into FicsIt-Networks is Lua. The reasons for using Lua instead of f.e. Python is simple. Lua is made for it. The whole Lua architecture is made with use in other programs in mind, that's like the whole purpose of Lua. So it is fast and easy to implement and also has a decent runtime speed. The simple syntax also makes it a great choice for beginners.

Visit the https://lua.org/[Lua Website] to learn more.

== External Libraries

The following list contains all available standard Lua libraries, non-standard libraries if they are reimplemented you can see the changes.

- math
- table
- string
- IO (only the File-Table)
- Serialization
- debug (parts of it for error handling)

=== Specialties

==== `coroutine.resume`

The `coroutine.resume` function got a small upgrade allowing for the implementation of multithreading.

You can use it just as usual, but if you add a parameter at the beginning
of the parameter list (before the thread) of type bool, and it is set to true,
then the resuming function will only keep executing until the end of this lua tick.
After that lua tick, the function will return, and you can do something else.

Important to note is though, you don't know if the resumed function yielded itself,
or if it was due to the end of the lua tick.
Since the return will contain nothing if it yielded based on the end of the lua tick.
With that said, also resuming a function that yielded that way with parameters will do nothing
about those parameters, they will just get dropped.

You should have a look at the xref:lua/examples/multiThreading.adoc[multi threading example] to find a use case for it.

== Additional Runtime Functions (besides APIs)

The lua runtime additionally has a couple of functions allowing you to search for different things of the reflection system and the game itself.

=== `Class findClass(string name)`

Tries to find an object type with the given name, and returns the found type.

=== `Class findStruct(string name)`

Tries to find a structure type with the given name, and returns the found type.

=== `ItemType findItem(string name)`

Tries to find an item type with the given name, and returns the found item type.
