= Lua
:description: Lua is a very nice simple and easy to learn language and is just made for use in other programs as scripting interface. This is the most powerful tool you have in FicsIt-Networks.

The first and most powerful coding language implement into FicsIt-Networks is Lua. The reasons for using Lua instead of f.e. Python is simple. Lua is made for it. The whole Lua architecture is made with use in other programs in mind, that's like the whole purpose of Lua. So it is fast and easy to implement and also has a decent runtime speed. The simple syntax also makes it a great choice for beginners.

Visit the https://lua.org/[Lua Website] to learn more.

== External Libraries

The following list contains all available standard Lua libraries, non-standard libraries if they are reimplemented you can see the changes.

- math
- table
- string
- IO (only the File-Table)
- Serialization

=== Specialties

==== `coroutine.resume`

The `coroutine.resume` function got a small upgrad allowing for the implementation of multithreading.

You can use it just as usual, but if you add a additional paramter at the beginning
of the paramter list (before the thread) of type bool and it is set to true,
then the resuming function will only keep executing until the end of this lua tick.
After that lua tick, the function will return and you can do something else.

Important to note is though, you dont know if the resumed function yielded it self,
or if it was due to the end of the lua tick.
Since the return will contain nothing if it yielded based on the end of the lua tick.
With that said, also resuming a function that yielded that way with paramters will do nothing
about those paramters, they will just get dropped.

You should have a look at the xref:lua/examples/multiThreading.adoc[multi threading example] to find a use case for it.

== Lua Instances

Lua Instances are speacial data-type FicsIt-Networks provides, allowing us to map a lot more easily different functions and properties of a game object to Lua.
These instances work through pre defined functions which are coded it the source code of the mod and through the usage of the so called refelction system of unreal.
Thanks to this, any other mod can very easily add support for FicsIt-Networks by simply filling a couple of conditions.

If you want to read the members such a instance has in runtime, you should use the `string[] getMembers()` method to get an array of member names the instance has.
If you pass `true` as the first parameter to the getMembers function, you will get a map of all the members where the membername is the key as string and a integer
is the value. `0` represents a function and `1` represents a property.

=== Properties

The instance can have properties (aka. attributes) you can interact with just like a variable.
For this use the `.` access operator.

Some properties are read only though, and if you try to write to them, a Lua exception gets thrown.

If a Instance refers to a network component, the instance will have a string property with the name "nick" which allows you to get/set
the nick of a component programatically and it will also have a read-only string property called "id" allowing you to get
the id of the component.

=== Functions

The instance can also have function allowing you to call subroutines. These function can have multiple input and output values.
To access such a member function you need to use the `:` member access operator or pass the instance as the first argument to the function.

== Lua Structs

Lua Structs work like a Lua Table with a special metatable attached.
Those Lua Structs just allow for a way simpler data management and are not required to be referenced to a object in the unreal reflection system.
Through that we can easily create and remove Lua Structs on the fly.
With that said, some Lua Structs can be implicitly constructed from a normal lua table which simply fullfills the criteria the struct gives
so it can be implicitly converted to such an struct when used in function parameters or write actions on properties.
